list: $/inerba/minigallery/models/gallery/columns.yaml
modelClass: Inerba\MiniGallery\Models\Gallery
title: GalleryController
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'inerba/minigallery/gallerycontroller/update/:id'
